env:
  browser: true
  es2020: true
  node: true
extends:
  - google
parserOptions:
  ecmaVersion: 12
ignorePatterns:
  - "site/"
  - "cache/"
  - "third_party/"
  - "test/"
  - "src/polyfill/"
  - "src/library*.js"
  - "src/runtime_*.js"
  - "src/shell*.js"
  - "src/preamble*.js"
  - "src/postamble*.js"
  - "src/closure-externs/"
  - "src/embind/"
  - "src/emrun_postjs.js"
  - "src/worker.js"
  - "src/wasm_worker.js"
  - "src/wasm2js.js"
  - "src/webGLClient.js"
  - "src/webGLWorker.js"
  - "src/*_shell_read.js"
  - "src/wasm_offset_converter.js"
  - "src/threadprofiler.js"
  - "src/cpuprofiler.js"
  - "src/memoryprofiler.js"
  - "src/support.js"
  - "src/gl-matrix.js"
  - "src/headless.js"
  - "src/headlessCanvas.js"
  - "src/emscripten-source-map.min.js"
  - "src/source_map_support.js"
  - "src/Fetch.js"
  - "src/settings.js"
  - "src/settings_internal.js"
  - "src/arrayUtils.js"
  - "src/deterministic.js"
  - "src/base64Utils.js"
  - "src/base64Decode.js"
  - "src/proxyWorker.js"
  - "src/proxyClient.js"
  - "src/IDBStore.js"
  - "src/URIUtils.js"
  - "tools/experimental"
rules:
  #max-len: ["error", 100]
  max-len: "off"
  no-multi-spaces: "off"
  require-jsdoc: "off"
  no-unused-vars: "off"
  arrow-body-style: ["error", "as-needed"]
  space-infix-ops: "error"
  quotes: ["error", "single", {"avoidEscape": true}]
